# Etekcity ZAP 3F 3-device remote with on & off buttons for each
# 10-BHC9938U
# 433.92 MHz
# B/N US02706K17
# Intertek 3159168
# Tested with rtl_433 -c Etekcity-ZAP-3F.conf - screenshot in PR

decoder {
        n=Etekcity-ZAP-3F,
        m=OOK_PWM,
        s=156,
        l=508,
        g=568,
        r=5508,
        bits>=25,
        repeats>=3,
        invert,
        get=@0:{16}:id,
        get=@16:{8}:button:[51:1-ON 60:1-OFF 195:2-ON 204:2-OFF 3:3-ON 12:3-OFF],
        unique
}
