#!/bin/sh
#
# Split the vendored, amalgamated Mongoose sources into their modules.
#
# rtl_433 vendors Mongoose 6.16 as two amalgamated files, src/mongoose.c and
# include/mongoose.h. That single ~16k-line .c file needs a lot of RAM to
# compile with optimization; on memory-constrained build hosts it can be
# cheaper to compile Mongoose as its ~30 original modules instead. This script
# reproduces that split. It is the CMake ENABLE_COMPILE_LOW_MEMORY option's
# code generator, but can also be run by hand:
#
#     tools/unamalgam.sh \
#         --amalgamated-c   src/mongoose.c \
#         --amalgamated-h   include/mongoose.h \
#         --out             build/mongoose
#
# The amalgamation carries '#ifdef MG_MODULE_LINES' / '#line 1 "path"' markers
# delimiting each original file, plus '/* Amalgamated: #include ... */'
# comments where a real '#include' used to be (the same scheme Cesanta's own
# tools use). This is a POSIX sh + awk implementation of the un-amalgamation:
# only sh and awk are required (no Python), which suits the minimal/embedded
# hosts this option targets. On top of the raw split it applies the small,
# deterministic adaptations rtl_433 needs to build the pieces as separate
# translation units instead of one; every adaptation is marked with an
# 'rtl_433' comment in the generated code. Mongoose 6.16 is end-of-life
# upstream, so the amalgamated input is frozen and the output is reproducible.

set -eu

AWK="${AWK:-awk}"

amalgamated_c=
amalgamated_h=
out=
while [ $# -gt 0 ]; do
    case "$1" in
        --amalgamated-c) amalgamated_c=$2; shift 2 ;;
        --amalgamated-h) amalgamated_h=$2; shift 2 ;;
        --out)           out=$2;           shift 2 ;;
        *) echo "unamalgam.sh: unknown argument: $1" >&2; exit 2 ;;
    esac
done
if [ -z "$amalgamated_c" ] || [ -z "$amalgamated_h" ] || [ -z "$out" ]; then
    echo "usage: unamalgam.sh --amalgamated-c FILE --amalgamated-h FILE --out DIR" >&2
    exit 2
fi

mkdir -p "$out"
manifest=$(mktemp)
trap 'rm -f "$manifest"' EXIT

# --- core splitter --------------------------------------------------------
# Reads one amalgamated file and writes each embedded module to its own file
# under OUT. Flattens the "mongoose/src/" prefix so mg_*.c / mg_*.h land at the
# top of OUT (siblings), while "common/..." keeps its layout; a single -I<OUT>
# then resolves both '#include "mg_internal.h"' and '#include "common/..."'.
# With DROP=1 it drops rtl_433's outer INCLUDE_MONGOOSE_H_ guard (present in
# the amalgamated header, absent from upstream's per-module headers) and
# records each written file in MANIFEST so trailing blank lines can be trimmed.
split_prog='
BEGIN { out = "" }
/^#ifdef .*_MODULE_LINES/ {
    getline marker
    if (match(marker, /"[^"]*"/))
        path = substr(marker, RSTART + 1, RLENGTH - 2)
    getline endif_line          # consume the marker block s closing #endif
    gsub(/\.\.\//, "", path)
    sub(/^mongoose\/src\//, "", path)
    if (out != "") close(out)
    full = OUT "/" path
    dir = full
    sub(/\/[^\/]*$/, "", dir)
    system("mkdir -p \"" dir "\"")
    out = full
    if (DROP) print full > MANIFEST
    next
}
{
    line = $0
    if (DROP && index(line, "INCLUDE_MONGOOSE_H_")) next
    # restore "/* Amalgamated: X */" back to "X"
    if (match(line, /\/\* Amalgamated: .* \*\//)) {
        m = substr(line, RSTART, RLENGTH)
        plen = length("/* Amalgamated: ")
        slen = length(" */")
        inner = substr(m, plen + 1, length(m) - plen - slen)
        line = substr(line, 1, RSTART - 1) inner substr(line, RSTART + RLENGTH)
    }
    if (out != "") print line > out
}
'

"$AWK" -v OUT="$out" -v DROP=1 -v MANIFEST="$manifest" "$split_prog" "$amalgamated_h"
"$AWK" -v OUT="$out" -v DROP=0 -v MANIFEST="$manifest" "$split_prog" "$amalgamated_c"

# Trim trailing blank lines from the header-split files (dropping the outer
# guard can leave a trailing blank at the end of the last module), matching the
# reference tool which rstrips those files to a single final newline.
trim_prog='
{ a[NR] = $0 }
END {
    last = 0
    for (i = NR; i >= 1; i--) if (a[i] != "") { last = i; break }
    for (i = 1; i <= last; i++) print a[i]
}
'
while IFS= read -r f; do
    "$AWK" "$trim_prog" "$f" > "$f.tmp" && mv "$f.tmp" "$f"
done < "$manifest"

# --- adaptations ----------------------------------------------------------
# Umbrella header: includes the per-module public headers in the exact order
# they appeared in the amalgamated mongoose.h, so consumers see identical
# declarations. Defines MG_INTERNAL empty (it defaults to 'static' in
# mg_internal.h) to give shared internal functions external linkage across the
# now-separate translation units.
cat > "$out/mongoose.h" <<'EOF'
/*
 * rtl_433: umbrella header for the un-amalgamated Mongoose 6.16 sources.
 *
 * Generated by tools/unamalgam.sh. Includes the individual public headers in
 * the exact order they appeared in the amalgamated include/mongoose.h, so the
 * resulting declarations are identical.
 */

#ifndef INCLUDE_MONGOOSE_H_
#define INCLUDE_MONGOOSE_H_

/*
 * The amalgamated build compiled all modules in a single translation unit,
 * where MG_INTERNAL functions could be 'static' (the default in
 * mg_internal.h). The un-amalgamated modules share these internal functions
 * across translation units, so they need external linkage here.
 */
#ifndef MG_INTERNAL
#define MG_INTERNAL
#endif

#include "mg_common.h"
#include "common/platform.h"
#include "common/platforms/platform_windows.h"
#include "common/platforms/platform_unix.h"
#include "common/platforms/platform_esp32.h"
#include "common/platforms/platform_esp8266.h"
#include "common/platforms/platform_cc3100.h"
#include "common/platforms/platform_cc3200.h"
#include "common/platforms/platform_cc3220.h"
#include "common/platforms/platform_msp432.h"
#include "common/platforms/platform_tm4c129.h"
#include "common/platforms/platform_mbed.h"
#include "common/platforms/platform_nrf51.h"
#include "common/platforms/platform_nrf52.h"
#include "common/platforms/simplelink/cs_simplelink.h"
#include "common/platforms/platform_wince.h"
#include "common/platforms/platform_nxp_lpc.h"
#include "common/platforms/platform_nxp_kinetis.h"
#include "common/platforms/platform_pic32.h"
#include "common/platforms/platform_rs14100.h"
#include "common/platforms/platform_stm32.h"
#include "common/platforms/lwip/mg_lwip.h"
#include "common/cs_md5.h"
#include "common/cs_sha1.h"
#include "common/cs_time.h"
#include "common/mg_str.h"
#include "common/mbuf.h"
#include "common/cs_base64.h"
#include "common/str_util.h"
#include "common/queue.h"
#include "mg_features.h"
#include "mg_net_if.h"
#include "mg_ssl_if.h"
#include "mg_net.h"
#include "mg_uri.h"
#include "mg_util.h"
#include "mg_http.h"
#include "mg_http_server.h"
#include "mg_http_client.h"
#include "mg_mqtt.h"
#include "mg_mqtt_server.h"
#include "mg_dns.h"
#include "mg_dns_server.h"
#include "mg_resolv.h"
#include "mg_coap.h"
#include "mg_sntp.h"
#include "mg_socks.h"

#endif /* INCLUDE_MONGOOSE_H_ */
EOF

# Every .c needs the build environment (feature macros) before its own
# includes, because several modules test those macros up front. Prepend the
# umbrella include to each module. (mg_http_modules.c is written afterwards, so
# it is deliberately not prepended.)
prepend='#include "mongoose.h" /* rtl_433: provide the amalgamated build environment */'
find "$out" -name '*.c' | while IFS= read -r f; do
    { printf '%s\n' "$prepend"; cat "$f"; } > "$f.tmp" && mv "$f.tmp" "$f"
done

# Insert text right after the prepended umbrella include (line 1), so the build
# environment is in effect before it.
insert_after_umbrella() {
    _f=$1
    _tmp="$_f.tmp"
    { head -n 1 "$_f"; printf '%s' "$2"; tail -n +2 "$_f"; } > "$_tmp"
    mv "$_tmp" "$_f"
}

# mg_net_if_socket.c / mg_net_if_socks.c test MG_ENABLE_NET_IF_* before
# including their own headers that define those macros; pull them in right
# after the umbrella. mg_net_if_socket.c also gets the MSG_NOSIGNAL fallback
# that lived at the top of the amalgamated mongoose.c (only its tcp_send uses
# it, and the raw split drops that top-of-file block).
insert_after_umbrella "$out/mg_net_if_socket.c" '#include "mg_net_if_socket.h" /* rtl_433: defines MG_ENABLE_NET_IF_SOCKET, tested below */
/* MSG_NOSIGNAL is Linux and most BSDs only, not macOS or Windows */
#ifndef MSG_NOSIGNAL
#define MSG_NOSIGNAL 0
#endif
'
insert_after_umbrella "$out/mg_net_if_socks.c" '#include "mg_net_if_socks.h" /* rtl_433: defines MG_ENABLE_NET_IF_SOCKS, tested below */
'
# The SSL backends use MG_CALLOC/MG_FREE/MG_SET_PTRPTR/DBG from mg_internal.h,
# which the amalgamation had already pulled in.
insert_after_umbrella "$out/mg_ssl_if_openssl.c" '#include "mg_internal.h" /* rtl_433: for MG_CALLOC, MG_FREE, MG_SET_PTRPTR, DBG */
'
insert_after_umbrella "$out/mg_ssl_if_mbedtls.c" '#include "mg_internal.h" /* rtl_433: for MG_CALLOC, MG_FREE, MG_SET_PTRPTR, DBG */
'

# Cross-TU prototypes for functions defined in mg_net.c but called from other
# modules; the amalgamation relied on the definitions appearing earlier in the
# same TU. Insert them right after the mg_forward() declaration in mg_internal.h.
internal_prog='
{ print }
index($0, "void mg_forward(struct mg_connection *from, struct mg_connection *to);") && !done {
    print "/* rtl_433: defined in mg_net.c, used by other modules; the amalgamated build"
    print " * relied on the definitions appearing earlier in the translation unit. */"
    print "void mg_if_get_conn_addr(struct mg_connection *nc, int remote,"
    print "                         union socket_address *sa);"
    print "void mg_sock_set(struct mg_connection *nc, sock_t sock);"
    done = 1
}
'
if ! grep -q "void mg_forward(struct mg_connection \*from, struct mg_connection \*to);" "$out/mg_internal.h"; then
    echo "unamalgam.sh: mg_forward anchor not found in mg_internal.h" >&2
    exit 1
fi
"$AWK" "$internal_prog" "$out/mg_internal.h" > "$out/mg_internal.h.tmp" \
    && mv "$out/mg_internal.h.tmp" "$out/mg_internal.h"

# mg_uri.c and the mg_http*.c modules share file-static definitions
# (parse_uri_component() in mg_uri.c; struct mg_http_proto_data and its
# accessors in mg_http.c), so they must compile as one translation unit, as
# they did in the amalgamation. This wrapper is that TU; the individual files
# are not compiled on their own.
cat > "$out/mg_http_modules.c" <<'EOF'
/*
 * rtl_433: these modules form a single translation unit, as they did in the
 * amalgamated build. The HTTP sub-modules (mg_http_cgi.c, mg_http_ssi.c,
 * mg_http_webdav.c, mg_http_websocket.c) use file-static definitions from
 * mg_http.c (struct mg_http_proto_data and its accessors), and mg_http.c
 * uses the static parse_uri_component() from mg_uri.c. The include order
 * matches the SOURCES list in mg_modules.mk.
 */

#include "mg_uri.c"
#include "mg_http.c"
#include "mg_http_cgi.c"
#include "mg_http_ssi.c"
#include "mg_http_webdav.c"
#include "mg_http_websocket.c"
EOF

echo "unamalgam.sh: wrote split Mongoose sources to $out" >&2
