#!/usr/bin/env python3
"""Split the vendored, amalgamated Mongoose sources into their modules.

rtl_433 vendors Mongoose 6.16 as two amalgamated files, ``src/mongoose.c``
and ``include/mongoose.h``. That single 16k-line .c file needs a lot of RAM
to compile with optimization; on memory-constrained build hosts it can be
cheaper to compile Mongoose as its ~30 original modules instead. This script
reproduces that split.

It is the CMake ``ENABLE_COMPILE_LOW_MEMORY`` option's code generator, but can
also be run by hand:

    tools/unamalgam.py \\
        --amalgamated-c   src/mongoose.c \\
        --amalgamated-h   include/mongoose.h \\
        --out             build/mongoose

The amalgamation carries ``#ifdef MG_MODULE_LINES`` / ``#line 1 "path"``
markers delimiting each original file, plus ``/* Amalgamated: #include ...
*/`` comments where a real ``#include`` used to be. This is the same scheme
Cesanta's own ``tools/unamalgam.py`` uses; the splitting core below is a
Python 3 port of it. On top of the raw split, this script applies the small
adaptations rtl_433 needs to build the pieces as separate translation units
(the amalgamation relied on being one TU). Every adaptation is marked with an
``rtl_433`` comment in the generated code and is deterministic, so the output
is reproducible; Mongoose 6.16 is end-of-life upstream, so the input never
changes.
"""

import argparse
import os
import re
import sys

MODULE_LINES_RE = re.compile(r'#ifdef .*_MODULE_LINES')
LINE_RE = re.compile(r'#line [01] "(.*)"')
AMALGAM_RE = re.compile(r'/\* Amalgamated: (.*) \*/')
# rtl_433's amalgamated include/mongoose.h wraps everything in this guard,
# which upstream's un-amalgamated headers do not have. Drop it so the split
# per-module headers stay balanced.
OUTER_GUARD_RE = re.compile(r'INCLUDE_MONGOOSE_H_')

# The amalgamation stores module paths like "mongoose/src/mg_net.c" and
# "common/cs_dbg.c". Flatten the "mongoose/src/" prefix so mg_*.c / mg_*.h
# land at the top of the output directory (siblings of each other), while the
# "common/..." tree keeps its layout. A single -I<out> then resolves both the
# sibling includes (#include "mg_internal.h") and #include "common/...".
FLATTEN_PREFIX = 'mongoose/src/'

PREPEND_INCLUDE = (
    '#include "mongoose.h" '
    '/* rtl_433: provide the amalgamated build environment */\n'
)

# Umbrella header: includes the per-module public headers in the exact order
# they appeared in the amalgamated mongoose.h, so consumers see identical
# declarations. Also defines MG_INTERNAL empty (it defaults to 'static' in
# mg_internal.h) to give shared internal functions external linkage across
# the now-separate translation units.
UMBRELLA_HEADER = '''\
/*
 * rtl_433: umbrella header for the un-amalgamated Mongoose 6.16 sources.
 *
 * Generated by tools/unamalgam.py. Includes the individual public headers in
 * the exact order they appeared in the amalgamated include/mongoose.h, so the
 * resulting declarations are identical.
 */

#ifndef INCLUDE_MONGOOSE_H_
#define INCLUDE_MONGOOSE_H_

/*
 * The amalgamated build compiled all modules in a single translation unit,
 * where MG_INTERNAL functions could be 'static' (the default in
 * mg_internal.h). The un-amalgamated modules share these internal functions
 * across translation units, so they need external linkage here.
 */
#ifndef MG_INTERNAL
#define MG_INTERNAL
#endif

#include "mg_common.h"
#include "common/platform.h"
#include "common/platforms/platform_windows.h"
#include "common/platforms/platform_unix.h"
#include "common/platforms/platform_esp32.h"
#include "common/platforms/platform_esp8266.h"
#include "common/platforms/platform_cc3100.h"
#include "common/platforms/platform_cc3200.h"
#include "common/platforms/platform_cc3220.h"
#include "common/platforms/platform_msp432.h"
#include "common/platforms/platform_tm4c129.h"
#include "common/platforms/platform_mbed.h"
#include "common/platforms/platform_nrf51.h"
#include "common/platforms/platform_nrf52.h"
#include "common/platforms/simplelink/cs_simplelink.h"
#include "common/platforms/platform_wince.h"
#include "common/platforms/platform_nxp_lpc.h"
#include "common/platforms/platform_nxp_kinetis.h"
#include "common/platforms/platform_pic32.h"
#include "common/platforms/platform_rs14100.h"
#include "common/platforms/platform_stm32.h"
#include "common/platforms/lwip/mg_lwip.h"
#include "common/cs_md5.h"
#include "common/cs_sha1.h"
#include "common/cs_time.h"
#include "common/mg_str.h"
#include "common/mbuf.h"
#include "common/cs_base64.h"
#include "common/str_util.h"
#include "common/queue.h"
#include "mg_features.h"
#include "mg_net_if.h"
#include "mg_ssl_if.h"
#include "mg_net.h"
#include "mg_uri.h"
#include "mg_util.h"
#include "mg_http.h"
#include "mg_http_server.h"
#include "mg_http_client.h"
#include "mg_mqtt.h"
#include "mg_mqtt_server.h"
#include "mg_dns.h"
#include "mg_dns_server.h"
#include "mg_resolv.h"
#include "mg_coap.h"
#include "mg_sntp.h"
#include "mg_socks.h"

#endif /* INCLUDE_MONGOOSE_H_ */
'''

# mg_uri.c and the mg_http*.c modules share file-static definitions
# (parse_uri_component() in mg_uri.c; struct mg_http_proto_data and its
# accessors in mg_http.c), so they must compile as one translation unit, as
# they did in the amalgamation. This wrapper is that TU; the individual files
# are not compiled on their own.
HTTP_MODULES_C = '''\
/*
 * rtl_433: these modules form a single translation unit, as they did in the
 * amalgamated build. The HTTP sub-modules (mg_http_cgi.c, mg_http_ssi.c,
 * mg_http_webdav.c, mg_http_websocket.c) use file-static definitions from
 * mg_http.c (struct mg_http_proto_data and its accessors), and mg_http.c
 * uses the static parse_uri_component() from mg_uri.c. The include order
 * matches the SOURCES list in mg_modules.mk.
 */

#include "mg_uri.c"
#include "mg_http.c"
#include "mg_http_cgi.c"
#include "mg_http_ssi.c"
#include "mg_http_webdav.c"
#include "mg_http_websocket.c"
'''

# The MSG_NOSIGNAL fallback lived at the very top of the amalgamated
# mongoose.c (before the first module marker, so the raw split drops it). It
# is only used by mg_net_if_socket.c's tcp_send, so it moves there.
MSG_NOSIGNAL_BLOCK = '''\
/* MSG_NOSIGNAL is Linux and most BSDs only, not macOS or Windows */
#ifndef MSG_NOSIGNAL
#define MSG_NOSIGNAL 0
#endif
'''

# Extra declarations for functions defined in mg_net.c but called from other
# TUs. In the amalgamation the definitions appeared earlier in the same TU,
# so no prototype was needed.
MG_INTERNAL_EXTRA = '''\
/* rtl_433: defined in mg_net.c, used by other modules; the amalgamated build
 * relied on the definitions appearing earlier in the translation unit. */
void mg_if_get_conn_addr(struct mg_connection *nc, int remote,
                         union socket_address *sa);
void mg_sock_set(struct mg_connection *nc, sock_t sock);
'''


def strip_amalgam_comment(line):
    """Turn '/* Amalgamated: #include "x" */' back into '#include "x"'."""
    return AMALGAM_RE.sub(r'\1', line)


def out_path(out_dir, module):
    """Map an amalgamation module path to its flattened output path."""
    module = re.sub(r'\.\./', '', module)
    if module.startswith(FLATTEN_PREFIX):
        module = module[len(FLATTEN_PREFIX):]
    return os.path.join(out_dir, module)


def split_file(amalgam_path, out_dir, drop_outer_guard):
    """Split one amalgamated file into its modules. Returns list of paths."""
    written = []
    ofile = None
    with open(amalgam_path) as f:
        it = iter(f)
        for line in it:
            if MODULE_LINES_RE.match(line):
                marker = next(it)
                m = LINE_RE.match(marker)
                if not m:
                    raise SystemExit(
                        'unamalgam: expected #line after %s marker in %s'
                        % (line.strip(), amalgam_path))
                path = out_path(out_dir, m.group(1))
                if ofile:
                    ofile.close()
                d = os.path.dirname(path)
                if d and not os.path.isdir(d):
                    os.makedirs(d)
                ofile = open(path, 'w')
                written.append(path)
                next(it)  # skip the trailing '#endif' of the marker block
            elif ofile is not None:
                if drop_outer_guard and OUTER_GUARD_RE.search(line):
                    continue  # rtl_433's outer include guard, not a module's
                ofile.write(strip_amalgam_comment(line))
    if ofile:
        ofile.close()
    if drop_outer_guard:
        # Dropping rtl_433's outer include guard can leave a trailing blank
        # line at the end of the last module; normalize to a single newline.
        for path in written:
            write(path, read(path).rstrip('\n') + '\n')
    return written


def read(path):
    with open(path) as f:
        return f.read()


def write(path, text):
    with open(path, 'w') as f:
        f.write(text)


def prepend(path, text):
    write(path, text + read(path))


def insert_after_umbrella(path, text):
    """Insert text right after the prepended '#include "mongoose.h"' line, so
    the build environment (feature macros) is in effect before it."""
    body = read(path)
    if not body.startswith(PREPEND_INCLUDE):
        raise SystemExit('unamalgam: %s missing umbrella include' % path)
    head = PREPEND_INCLUDE
    write(path, head + text + body[len(head):])


def apply_adaptations(out_dir):
    """Apply the rtl_433-local fixes needed to build the split as separate TUs."""
    # Umbrella header consumed by every module (and by rtl_433 itself).
    write(os.path.join(out_dir, 'mongoose.h'), UMBRELLA_HEADER)

    # Every .c needs the build environment (feature macros) before its own
    # includes, because several modules test those macros up front.
    for root, _dirs, files in os.walk(out_dir):
        for name in files:
            if name.endswith('.c'):
                prepend(os.path.join(root, name), PREPEND_INCLUDE)

    # mg_net_if_socket.c / mg_net_if_socks.c test MG_ENABLE_NET_IF_* before
    # including their own headers that define those macros; pull them in right
    # after the umbrella. mg_net_if_socket.c also gets the moved MSG_NOSIGNAL
    # fallback.
    insert_after_umbrella(
        os.path.join(out_dir, 'mg_net_if_socket.c'),
        '#include "mg_net_if_socket.h" '
        '/* rtl_433: defines MG_ENABLE_NET_IF_SOCKET, tested below */\n'
        + MSG_NOSIGNAL_BLOCK)
    insert_after_umbrella(
        os.path.join(out_dir, 'mg_net_if_socks.c'),
        '#include "mg_net_if_socks.h" '
        '/* rtl_433: defines MG_ENABLE_NET_IF_SOCKS, tested below */\n')

    # The SSL backends use MG_CALLOC/MG_FREE/MG_SET_PTRPTR/DBG from
    # mg_internal.h, which the amalgamation had already pulled in.
    for name in ('mg_ssl_if_openssl.c', 'mg_ssl_if_mbedtls.c'):
        insert_after_umbrella(
            os.path.join(out_dir, name),
            '#include "mg_internal.h" '
            '/* rtl_433: for MG_CALLOC, MG_FREE, MG_SET_PTRPTR, DBG */\n')

    # Cross-TU prototypes for functions defined in mg_net.c.
    internal_h = os.path.join(out_dir, 'mg_internal.h')
    text = read(internal_h)
    anchor = 'void mg_forward(struct mg_connection *from, struct mg_connection *to);\n'
    if anchor not in text:
        raise SystemExit('unamalgam: mg_forward anchor not found in mg_internal.h')
    write(internal_h, text.replace(anchor, anchor + MG_INTERNAL_EXTRA, 1))

    # Combined HTTP/URI translation unit.
    write(os.path.join(out_dir, 'mg_http_modules.c'), HTTP_MODULES_C)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--amalgamated-c', required=True,
                    help='path to the amalgamated mongoose.c')
    ap.add_argument('--amalgamated-h', required=True,
                    help='path to the amalgamated mongoose.h')
    ap.add_argument('--out', required=True,
                    help='output directory for the split modules')
    args = ap.parse_args()

    out_dir = args.out
    if not os.path.isdir(out_dir):
        os.makedirs(out_dir)

    split_file(args.amalgamated_h, out_dir, drop_outer_guard=True)
    split_file(args.amalgamated_c, out_dir, drop_outer_guard=False)
    apply_adaptations(out_dir)
    print('unamalgam: wrote split Mongoose sources to %s' % out_dir,
          file=sys.stderr)


if __name__ == '__main__':
    main()
