name: Build with CMake and Autotools
on: [push, pull_request]
jobs:
  build_check_job:
    runs-on: ubuntu-latest
    name: build project
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run CMake+Ninja
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        buildDirectory: '${{runner.workspace}}/b/ninja'
        cmakeAppendedArgs: '-GNinja -DENABLE_RTLSDR=OFF -DENABLE_SOAPYSDR=OFF'
    - name: Run CMake+UnixMakefiles
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        buildDirectory: '${{runner.workspace}}/b/unixmakefiles'
        cmakeAppendedArgs: '-G "Unix Makefiles" -DENABLE_RTLSDR=OFF -DENABLE_SOAPYSDR=OFF'
    - name: Autotools autoreconf
      run: autoreconf --install
    - name: Autotools configure
      run: ./configure
    - name: Autotools make
      run: make
